export const drugs = [
  {name: 'Abacavir'},
  {name: 'Abacavir / dolutegravir / lamivudine (Triumeq®)'},
  {name: 'Abacavir / lamivudine (Epzicom®)'},
  {name: 'Acyclovir'},
  {name: 'Alemtuzumab'},
  {name: 'Alendronate'},
  {name: 'Allopurinol'},
  {name: 'Amifostine'},
  {name: 'Amikacin'},
  {name: 'Aminocaproic Acid'},
  {name: 'Amitriptyline'},
  {name: 'Amlodipine'},
  {name: 'Amoxicillin'},
  {name: 'Amoxicillin / clavulanic acid'},
  {name: 'Amphotericin B'},
  {name: 'Ampicillin'},
  {name: 'Anti-Inhibitor Coagulant Complex (FEIBA)'},
  {name: 'Anti-thymocyte globulin'},
  {name: 'Aprepitant'},
  {name: 'Asparaginase'},
  {name: 'Atazanavir (Reyataz®)'},
  {name: 'Atenolol'},
  {name: 'Atovaquone'},
  {name: 'Azithromycin'},
  {name: 'Baclofen'},
  {name: 'Bleomycin'},
  {name: 'Bortezomib'},
  {name: 'Bosentan'},
  {name: 'Busulfan'},
  {name: 'Calcium'},
  {name: 'Captopril'},
  {name: 'Carbamazepine'},
  {name: 'Carboplatin'},
  {name: 'Carmustine'},
  {name: 'Cefaclor'},
  {name: 'Cefepime'},
  {name: 'Cefixime'},
  {name: 'Ceftazidime'},
  {name: 'Cefuroxime'},
  {name: 'Celecoxib'},
  {name: 'Cephalexin'},
  {name: 'Cidofovir'},
  {name: 'Cisplatin'},
  {name: 'Cladribine'},
  {name: 'Clarithromycin'},
  {name: 'Clindamycin'},
  {name: 'Clobazam'},
  {name: 'Clofarabine'},
  {name: 'Codeine'},
  {name: 'Crizanlizumab'},
  {name: 'Crizotinib'},
  {name: 'Cyclobenzaprine'},
  {name: 'Cyclophosphamide'},
  {name: 'Cyclosporine'},
  {name: 'Cyproheptadine'},
  {name: 'Cytarabine'},
  {name: 'Dacarbazine'},
  {name: 'Dactinomycin'},
  {name: 'Dapsone'},
  {name: 'Darunavir (Prezista®)'},
  {name: 'Dasatinib'},
  {name: 'Daunorubicin'},
  {name: 'Deferasirox (Exjade®)'},
  {name: 'Desmopressin (Stimate®)'},
  {name: 'Dexamethasone'},
  {name: 'Diclofenac'},
  {name: 'Didanosine'},
  {name: 'Dinutuximab'},
  {name: 'Dobutamine'},
  {name: 'Dopamine'},
  {name: 'Dornase alfa'},
  {name: 'Doxorubicin'},
  {name: 'Dronabinol'},
  {name: 'Efavirenz'},
  {name: 'Efavirenz / emtricitabine / tenofovir (Atripla®)'},
  {name: 'Eltrombopag'},
  {name: 'Elvitegravir / cobicistat / emtricitabine / tenofovir (Stribild®)'},
  {name: 'Elvitegravir / cobicistat / emtricitabine / tenofovir alafenamide (Genvoya®)'},
  {name: 'Emicizumab'},
  {name: 'Emtricitabine (Emtriva®)'},
  {name: 'Emtricitabine / rilpivirine / tenofovir alafenamide (Odefsey®)'},
  {name: 'Emtricitabine / tenofovir (Truvada®)'},
  {name: 'Emtricitabine / tenofovir alafenamide (Descovy®)'},
  {name: 'Enalapril'},
  {name: 'Enoxaparin'},
  {name: 'Erlotinib'},
  {name: 'Erythromycin'},
  {name: 'Erythropoietin'},
  {name: 'Etonogestrel (Nexplanon®)'},
  {name: 'Etoposide'},
  {name: 'Etravirine (Intelence®)'},
  {name: 'Factor IX complex'},
  {name: 'Factor IX concentrate'},
  {name: 'Factor VIIa (Recombinant)'},
  {name: 'Factor VIII (Human) and von Willebrand Factor'},
  {name: 'Factor VIII (Recombinant)'},
  {name: 'Famciclovir'},
  {name: 'Famotidine'},
  {name: 'Fidaxomicin'},
  {name: 'Fluconazole'},
  {name: 'Fludarabine'},
  {name: 'Fluorouracil'},
  {name: 'Foscarnet'},
  {name: 'Furosemide'},
  {name: 'G-CSF (Filgrastim)'},
  {name: 'Gabapentin'},
  {name: 'Ganciclovir'},
  {name: 'Gefitinib'},
  {name: 'Gemcitabine'},
  {name: 'Gemtuzumab ozogamicin'},
  {name: 'GM-CSF (Sargramostim)'},
  {name: 'Granisetron'},
  {name: 'Heparin Lock Flush for children and young adults'},
  {name: 'Heparin Lock Flush for infants'},
  {name: 'Hydralazine'},
  {name: 'Hydrocodone with acetaminophen'},
  {name: 'Hydrocortisone'},
  {name: 'Hydromorphone'},
  {name: 'Hydroxyurea'},
  {name: 'Hydroxyurea for sickle cell disease'},
  {name: 'Ifosfamide'},
  {name: 'Imatinib'},
  {name: 'Imipenem / cilastatin'},
  {name: 'Immune globulin'},
  {name: 'Interferon alfa-2a and alfa-2b'},
  {name: 'Interferon alfa-2b for melanoma'},
  {name: 'Interleukin-2 (Aldesleukin)'},
  {name: 'Irinotecan'},
  {name: 'Isotretinoin'},
  {name: 'Itraconazole'},
  {name: 'Ketoconazole'},
  {name: 'L-glutamine'},
  {name: 'Labetalol'},
  {name: 'Lamivudine'},
  {name: 'Leucovorin with high dose methotrexate (HDMTX)'},
  {name: 'Levothyroxine'},
  {name: 'Linezolid'},
  {name: 'Lomustine'},
  {name: 'Lopinavir / Ritonavir (Kaletra®)'},
  {name: 'Lorazepam'},
  {name: 'Lorlatinib'},
  {name: 'Magnesium'},
  {name: 'Maraviroc (Selzentry®)'},
  {name: 'Mechlorethamine'},
  {name: 'Megestrol acetate'},
  {name: 'Meloxicam'},
  {name: 'Melphalan'},
  {name: 'Meperidine'},
  {name: 'Mercaptopurine'},
  {name: 'Meropenem'},
  {name: 'Mesna'},
  {name: 'Methadone'},
  {name: 'Methotrexate'},
  {name: 'Methylphenidate'},
  {name: 'Metronidazole'},
  {name: 'Micafungin'},
  {name: 'Mitotane'},
  {name: 'Mitoxantrone'},
  {name: 'Modafinil'},
  {name: 'Morphine'},
  {name: 'Muromonab CD3'},
  {name: 'Mycophenolate mofetil'},
  {name: 'Nelarabine'},
  {name: 'Nelfinavir'},
  {name: 'Neuromuscular blockers'},
  {name: 'Nevirapine'},
  {name: 'Norepinephrine'},
  {name: 'Omeprazole'},
  {name: 'Ondansetron'},
  {name: 'Oxycodone'},
  {name: 'Paclitaxel'},
  {name: 'PEGaspargase'},
  {name: 'Pegfilgrastim'},
  {name: 'Pemetrexed'},
  {name: 'Penicillin VK'},
  {name: 'Pentamidine (inhaled by mouth)'},
  {name: 'Phenobarbital'},
  {name: 'Phenytoin'},
  {name: 'Phosphorus'},
  {name: 'Posaconazole'},
  {name: 'Potassium'},
  {name: 'Prednisone'},
  {name: 'Probenecid'},
  {name: 'Procarbazine'},
  {name: 'Promethazine'},
  {name: 'Promethazine topical gel'},
  {name: 'Propoxyphene'},
  {name: 'Raltegravir (Isentress®)'},
  {name: 'Ranitidine'},
  {name: 'Rasburicase'},
  {name: 'Regorafenib'},
  {name: 'Rilpivirine (Edurant®)'},
  {name: 'Rilpivirine / emtricitabine / tenofovir (Complera®)'},
  {name: 'Ritonavir'},
  {name: 'Rituximab'},
  {name: 'Rivaroxaban'},
  {name: 'Ruxolitinib'},
  {name: 'Sacubitril/valsartan (Entresto®)'},
  {name: 'Saquinavir'},
  {name: 'Sirolimus'},
  {name: 'Sorafenib'},
  {name: 'Stavudine'},
  {name: 'Sucralfate'},
  {name: 'Sugammadex'},
  {name: 'Sunitinib'},
  {name: 'Tacrolimus'},
  {name: 'Temozolomide'},
  {name: 'Teniposide'},
  {name: 'Tenofovir'},
  {name: 'Thioguanine'},
  {name: 'Thiotepa'},
  {name: 'Tobramycin'},
  {name: 'Topotecan'},
  {name: 'Tretinoin applied to the skin'},
  {name: 'Tretinoin by mouth'},
  {name: 'Trimethoprim / sulfamethoxazole'},
  {name: 'Valproic acid'},
  {name: 'Vancomycin'},
  {name: 'Vinblastine'},
  {name: 'Vincristine'},
  {name: 'Voriconazole'},
  {name: 'Vorinostat'},
  {name: 'Voxelotor'},
  {name: 'Warfarin'},
  {name: 'Zidovudine'},
  {name: 'Zidovudine / Lamivudine (Combivir®)'},
  {name: 'Related Links'},
  {name: 'Patient/Family Education Materials'},
  {name: 'Infection Control Tips'},
  {name: 'Medicines'},
  {name: 'MEDminder™ Card'},
  {name: 'Related LinksClose'},
  {name: 'Share'}
];